name: Build and deploy ASP.Net Core app to Azure Web App - clara-copilot-agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build with dotnet
        run: dotnet build src/Clara.API/Clara.API.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish src/Clara.API/Clara.API.csproj -c Release -o ./publish

      - name: Zip published output
        run: Compress-Archive -Path ./publish/* -DestinationPath ./publish.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BA3A0F365AFF4FB4B676A4098CA1DB6B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_50F9126701734273AD41F93E8FACCF45 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_039026222E744853AA195A60DC8B0E13 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'clara-copilot-agent'
          slot-name: 'Production'
          package: publish.zip
