name: Build and deploy ASP.Net Core app to Azure Web App - clara-copilot-agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout
      id-token: write # Add this line to allow fetching federated token

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 'v8.0'

      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore "src/clara.api/clara.api.csproj"
          dotnet build --configuration Release "src/clara.api/clara.api.csproj"
          dotnet publish -c Release "src/clara.api/clara.api.csproj" -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_83814A26E18C461AB094B47E0002C03D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CC3AD74419C24AA981B6F6C45B08B3E2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8DF6156CBAD54664A6E751A02CC6A506 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'clara-copilot-agent'
          slot-name: 'Production'
          package: .
