name: Build and deploy ASP.Net Core app to Azure Web App - clara-copilot-agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build with dotnet
        run: dotnet build src/Clara.API/Clara.API.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish src/Clara.API/Clara.API.csproj -c Release -o ./publish

      - name: Zip published output
        run: Compress-Archive -Path ./publish/* -DestinationPath ./publish.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish.zip

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: List files for debug
        run: dir

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A2D7F044FB164DAF909FBCC1437E13B2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_11EA92CC66984F19A0ED2F2B040442DC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DF2DFDE333D5457D9D71F883EFE85F4B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'clara-copilot-agent'
          slot-name: 'Production'
          package: publish.zip
